USE online_food_delivery;
CREATE TABLE CUSTOMER
(CUSTOMER_ID INT PRIMARY KEY,
CUSTOMER_NAME VARCHAR (60),
EMAIL VARCHAR (60),
CITY VARCHAR (60),
SIGN_UP_DATE DATE);

CREATE TABLE RESTAURANT
(RESTAURANT_ID INT PRIMARY KEY,
RESTAURANT_NAMME VARCHAR (60),
CITY VARCHAR (60),
 REG_DATE DATE);
 
 
 CREATE TABLE MANU
 (ITEM_ID INT PRIMARY KEY,
 RESTAURANT_ID INT,
 ITEM_NAME VARCHAR (60),
 PRICE DECIMAL(10,2),
 CONSTRAINT FK_MANU_REST
 FOREIGN KEY (RESTAURANT_ID)
 REFERENCES RESTAURANT (RESTAURANT_ID)
 );

SELECT  ITEM_NAME,PRICE FROM MANU
WHERE PRICE>=300
ORDER BY PRICE DESC
LIMIT 5; 

SELECT COUNT(DISTINCT ITEM_NAME) AS UNIQUE_MANU FROM MANU;

SELECT ITEM_ID,ITEM_NAME FROM MANU
WHERE ITEM_NAME = 'Rasgulla';

DROP TABLE IF EXISTS ORDERS;

CREATE TABLE ORDERS
(ORDER_ID INT PRIMARY KEY,
CUSTOMER_ID INT,
RESTAURANT_ID INT,
ORDER_DATE DATE,
CONSTRAINT FK_NAME1 FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
CONSTRAINT FK_NAME2 FOREIGN KEY(RESTAURANT_ID) REFERENCES RESTAURANT(RESTAURANT_ID));

CREATE TABLE ORDERS_DETAILS
(ORDER_DETAIL_ID INT PRIMARY KEY,
ORDER_ID INT,
ITEM_ID INT,
QUANTITY INT,
CONSTRAINT FK_NAME3 FOREIGN KEY(ORDER_ID) REFERENCES ORDERS(ORDER_ID),
CONSTRAINT FK_NAME4 FOREIGN KEY(ITEM_ID) REFERENCES MANU(ITEM_ID));

SELECT CUSTOMER_NAME,COUNT(ORDER_ID) AS NUMBER_ORDERS
FROM CUSTOMER AS C JOIN ORDERS AS O 
ON C.CUSTOMER_ID=O.CUSTOMER_ID
GROUP BY CUSTOMER_NAME
ORDER BY NUMBER_ORDERS DESC;

SELECT COUNT(ORDER_DETAIL_ID),COUNT(ORDER_ID) FROM ORDERS_DETAILS;  

SELECT ITEM_NAME,COUNT(ORDER_DETAIL_ID) AS NUM_ORDERS FROM 
ORDERS_DETAILS AS OD LEFT JOIN MANU AS MU
ON OD.ITEM_ID=MU.ITEM_ID	
GROUP BY ITEM_NAME
ORDER BY NUM_ORDERS DESC;

SELECT ORDER_ID,SUM(PRICE) FROM 
ORDERS_DETAILS AS OD LEFT JOIN MANU AS MU
ON OD.ITEM_ID=MU.ITEM_ID	
GROUP BY ORDER_ID
ORDER BY SUM(PRICE) DESC
LIMIT 5;

SELECT CITY,SUM(PRICE*QUANTITY) AS TOTAL_REVENUE FROM
ORDERS_DETAILS AS OD LEFT JOIN MANU AS MU
ON OD.ITEM_ID=MU.ITEM_ID
JOIN RESTAURANT AS R ON 
 MU.RESTAURANT_ID = R.RESTAURANT_ID
 GROUP BY CITY;
 
 SELECT CITY,COUNT(ORDER_ID) AS TOTAL_ORDERS
 FROM RESTAURANT AS R JOIN ORDERS AS O ON
 R.RESTAURANT_ID = O.RESTAURANT_ID
 GROUP BY CITY
 HAVING TOTAL_ORDERS >5;
 
 SELECT ITEM_NAME,SUM(PRICE*QUANTITY) AS TOTAL_REVENUE FROM
 MANU AS MU JOIN ORDERS_DETAILS AS OD ON
 MU.ITEM_ID = OD.ITEM_ID
 GROUP BY ITEM_NAME
 HAVING (TOTAL_REVENUE) >1000;
 
SELECT ITEM_NAME,PRICE,(SELECT AVG(PRICE) FROM MANU) FROM MANU

SELECT CUSTOMER_ID,CUSTOMER_NAME FROM CUSTOMER
WHERE CUSTOMER_ID IN (SELECT CUSTOMER_ID FROM ORDERS);

SELECT MONTH(ORDER_DATE) AS MONTH_NO,MONTHNAME(ORDER_DATE) AS MONTH_NAME,COUNT(ORDER_ID) AS TOTAL_ORDERS FROM ORDERS
GROUP BY MONTH_NO,MONTH_NAME
ORDER BY MONTH_NO;

SELECT CITY,SUM(PRICE*QUANTITY) AS TOTAL_REVENUE 
FROM CUSTOMER AS C JOIN ORDERS AS OD ON C.CUSTOMER_ID=OD.CUSTOMER_ID
JOIN ORDERS_DETAILS AS O ON OD.ORDER_ID=O.ORDER_ID
JOIN MANU AS MU ON O.ITEM_ID=MU.ITEM_ID
GROUP BY CITY
ORDER BY TOTAL_REVENUE DESC
LIMIT 3